---
- name: Ansible check file paths exists.
  stat:
    path: "{{ item }}"
  with_items: "{{ paths }}"
  register: validate_paths

- debug:
    msg: "exist: {{ item.stat.exists }} isdir: {{ item.stat.isdir }}"
  with_items: "{{ validate_paths.results }}"
  when: item.stat.exists == True and item.stat.isdir == False
  